import { CompanyTemplate, MyMaxTemplateMenu, MyMaxIndivReportingMenu } from './index';

export class SessionUser {

    constructor (public P6_userUID: string,
        public sFirstname: string,
        public sLastName: string,
        public sFullName: string,
        public sGender: string,
        public sLoginName: string,
        public sLoginPassword: string,
        public sEmail: string,
        public P5Corp_userUID: string,
        public P5Cricket_userUID: string,
        public P5Sport_userUID: string,
        public Esurvey_userUID: string,
        public profilePhoto: string,
        public companyLogo: string,
        public pdfBackground: string,
        public companyPdfLogo: string,
        public status: string,
        public bIsManager: boolean,
        public bIsSecondManager: boolean,
        public bIsSuperUser: boolean,
        public bIsGlobalUser: boolean,
        public sJobTitle: string,
        public sJobTitleUUID: string,
        public P5ClientUID: string,
        public organisationTiersUUID: string,
        public P6CompanyUID: string,
        public bIsAssessmentParticipant: boolean,
        public companytemplate: CompanyTemplate,
        public dPouchDateCreated: string,
        public dPouchDateUpdated: string,
        public bShowPDPLink: boolean,
        public bShowMidYearReviewLink: boolean,
        public bShowPerformanceReviewLink: boolean,
        public bShowPerformanceAgreementLink: boolean,
        public SupportMessageSubjectUID: string,
        public sMobileNumber: string,
        public sWorkPhoneNumber: string,
        public sWorkPhoneExtension: string,
        public dDateJoined: string,
        public iYearsWorked: string,
        public iMonthsWorked: string,
        public iDaysWorked: string
    ) { }
}
