// export { LayoutAdminGenericComponent } from './pt-layout-admin-generic/pt-layout-admin-generic.component';
export { LayoutChooseQuestionnaireComponent } from './pt-layout-choose-questionnaire/pt-layout-choose-questionnaire.component';
export { LayoutContributionScorecardComponent } from './pt-layout-contribution-scorecard/pt-layout-contribution-scorecard.component';
export { LayoutConversationFeedComponent } from './pt-layout-conversation-report/pt-layout-conversation-report.component';
export { LayoutEsurveyAssessmentComponent } from './pt-layout-esurvey-assessment/pt-layout-esurvey-assessment.component';
export { LayoutExpertiseReviewReportsComponent } from './pt-layout-expertise-review-report/pt-layout-expertise-review-report.component';
export { LayoutPDPReportComponent } from './pt-layout-pdp/pt-layout-pdp.component';
export { LayoutIntegratedPDPReportComponent } from './pt-layout-integrated-pdp/pt-layout-integrated-pdp.component';
export { LayoutPerformanceAgreementsComponent } from './pt-layout-performance-agreements/pt-layout-performance-agreements.component';
export { LayoutPerformanceReviewsComponent } from './pt-layout-performance-reviews/pt-layout-performance-reviews.component';
// export { LayoutPeriodSummaryComponent } from './pt-layout-period-summary/pt-layout-period-summary.component';
// export { LayoutSelfAssessmentReportsComponent } from './pt-layout-self-assessment/pt-layout-self-assessment.component';
export { LayoutSwotReportComponent } from './pt-layout-swot-analysis/pt-layout-swot-analysis.component';
export { LayoutThreesixtyReportsComponent } from './pt-layout-threesixty-report/pt-layout-threesixty-report.component';
// export { LayoutSafetyMetricComponent } from './pt-layout-safety-metric/pt-layout-safety-metric.component';
export { LayoutPersonalPortfolioComponent } from './pt-layout-personal-portfolio/pt-layout-personal-portfolio.component';
export { LayoutExitInterviewReportsComponent } from './pt-layout-exit-interview-report/pt-layout-exit-interview-report.component';
// export { LayoutCompanyScorecardComponent } from './pt-layout-company-scorecard/pt-layout-company-scorecard.component';
export { LayoutRecruitmentReportsComponent } from './pt-layout-recruitment-report/pt-layout-recruitment-report.component';
